#!/bin/bash

export SEARCH_BINARY_ENABLED=false
export SEARCH_INITIAL_ARRAY_SIZE=511
export SEARCH_MIN_AMOUNT=22
export SEARCH_TO_FLAT_THRESHOLD=31
export SEARCH_FLAT_SIZE=3

export DIGGER_MIN_DEPTH=3
export DIGGER_MAX_DEPTH=10
export DIGGER_MIN_DEPTH_PROBABILITY=100

export ATTORNEY_LICENSE_MIN_COST=1
export ATTORNEY_LICENSE_MAX_COST=1
export ATTORNEY_FREE_LICENSE_PROBABILITY=100
export ATTORNEY_HTTP_TIMEOUT_MS=150

export HTTP_TIMEOUT_MS=550

export SEARCH_EXPLORERS_NUM=16
export ATTORNEYS_NUM=16
export DIGGERS_NUM=8
export ACCOUNTANT_NUM=8

export MAX_RPS=1000
export EXPLORE_PHASE1_RPS=950
export ACCOUNTANT_PHASE1_RPS=1
export DIGGER_PHASE1_RPS=500
export ATTORNEY_PHASE1_RPS=350

export ENABLE_PHASED=true
export PHASE2_START=30

export EXPLORE_PHASE2_RPS=1
export ACCOUNTANT_PHASE2_RPS=200
export DIGGER_PHASE2_RPS=1
export ATTORNEY_PHASE2_RPS=1

export AREA_CHAN_CAP=5
export TILE_CHAN_CAP=5
export LICENSE_CHAN_CAP=30
export EMPTY_LICENSE_CHAN_CAP=30
export TREASURE_CHAN_CAP=40000

cargo build --release
./target/release/hl21